import crypto from 'node:crypto';
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const rootDir = path.resolve(fileURLToPath(new URL('..', import.meta.url)));

export function parseArgs(argv = process.argv.slice(2)) {
  const args = {};

  for (let i = 0; i < argv.length; i += 1) {
    const item = argv[i];

    if (!item.startsWith('--')) {
      args._ = args._ || [];
      args._.push(item);
      continue;
    }

    const [rawKey, inlineValue] = item.slice(2).split('=', 2);
    const key = rawKey.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());

    if (inlineValue !== undefined) {
      args[key] = inlineValue;
      continue;
    }

    const next = argv[i + 1];
    if (next && !next.startsWith('--')) {
      args[key] = next;
      i += 1;
    } else {
      args[key] = true;
    }
  }

  return args;
}

export async function readJson(filePath, fallback = null) {
  try {
    return JSON.parse(await fsp.readFile(filePath, 'utf8'));
  } catch (error) {
    if (fallback !== null && error.code === 'ENOENT') {
      return fallback;
    }
    throw error;
  }
}

export async function writeJson(filePath, data) {
  await ensureDir(path.dirname(filePath));
  const tempPath = `${filePath}.${process.pid}.${crypto.randomBytes(6).toString('hex')}.tmp`;
  await fsp.writeFile(tempPath, `${JSON.stringify(data, null, 2)}\n`);
  await fsp.rename(tempPath, filePath);
}

export async function ensureDir(dirPath) {
  await fsp.mkdir(dirPath, { recursive: true });
}

export async function listDirectories(dirPath) {
  const entries = await fsp.readdir(dirPath, { withFileTypes: true });
  return entries.filter((entry) => entry.isDirectory()).map((entry) => entry.name).sort();
}

export function sha256(value) {
  return crypto.createHash('sha256').update(value).digest('hex');
}

export function compactHash(value) {
  return sha256(value).slice(0, 12);
}

export function utcStamp() {
  return new Date().toISOString().replace(/[-:]/g, '').replace(/\.\d{3}Z$/, 'Z');
}

export function stripNumericPrefix(slug) {
  return slug.replace(/^\d+-/, '');
}

export function pascalCase(slug) {
  return stripNumericPrefix(slug)
    .split('-')
    .filter(Boolean)
    .map((part) => part.slice(0, 1).toUpperCase() + part.slice(1))
    .join('');
}

export async function copyDir(source, destination) {
  await fsp.rm(destination, { recursive: true, force: true });
  await fsp.cp(source, destination, {
    recursive: true,
    filter: (sourcePath) => !sourcePath.includes(`${path.sep}node_modules${path.sep}`),
  });
}

export async function readIfExists(filePath) {
  try {
    return await fsp.readFile(filePath, 'utf8');
  } catch (error) {
    if (error.code === 'ENOENT') {
      return '';
    }
    throw error;
  }
}

export async function pathExists(filePath) {
  return fs.existsSync(filePath);
}

export function mergePackageJson(basePackage, preset = {}) {
  const next = structuredClone(basePackage);

  for (const key of ['dependencies', 'devDependencies']) {
    next[key] = {
      ...(next[key] || {}),
      ...(preset[key] || {}),
    };
  }

  return next;
}

export function renderClaudeMcpConfig(mcpServers = {}) {
  return JSON.stringify({ mcpServers }, null, 2);
}

export function renderCodexConfig(mcpServers = {}, projectDirs = []) {
  const lines = [];

  for (const [name, server] of Object.entries(mcpServers)) {
    lines.push(`[mcp_servers.${name}]`);
    lines.push(`command = ${JSON.stringify(server.command)}`);
    lines.push(`args = ${JSON.stringify(server.args || [])}`);

    if (server.env && Object.keys(server.env).length > 0) {
      const env = Object.entries(server.env)
        .map(([key, value]) => `${key} = ${JSON.stringify(value)}`)
        .join(', ');
      lines.push(`env = { ${env} }`);
    }

    lines.push('');
  }

  for (const projectDir of [...new Set(projectDirs)]) {
    lines.push(`[projects.${JSON.stringify(projectDir)}]`);
    lines.push('"trust_level" = "trusted"');
    lines.push('');
  }

  lines.push('[plugins."github@openai-curated"]');
  lines.push('enabled = true');
  lines.push('');

  lines.push(`# Generated by explore-design-md.`);
  return `${lines.join('\n').trim()}\n`;
}

export async function updateManifest(runId, patch) {
  const manifestPath = path.join(rootDir, 'results', 'manifest.json');
  await withLock(`${manifestPath}.lock`, async () => {
    const manifest = await readJson(manifestPath, []);
    const runMetadata = await readJson(path.join(rootDir, 'runs', runId, 'run.json'), {});
    const index = manifest.findIndex((entry) => entry.runId === runId);

    if (index === -1) {
      manifest.push({ ...runMetadata, runId, ...patch });
    } else {
      manifest[index] = { ...runMetadata, ...manifest[index], ...patch };
    }

    await writeJson(manifestPath, manifest.sort((a, b) => a.runId.localeCompare(b.runId)));
  });
}

export async function loadManifest() {
  return readJson(path.join(rootDir, 'results', 'manifest.json'), []);
}

async function withLock(lockPath, callback) {
  const startedAt = Date.now();

  while (true) {
    try {
      await fsp.mkdir(lockPath);
      break;
    } catch (error) {
      if (error.code !== 'EEXIST') {
        throw error;
      }

      if (Date.now() - startedAt > 30000) {
        throw new Error(`Timed out waiting for lock: ${lockPath}`);
      }

      await sleep(50);
    }
  }

  try {
    return await callback();
  } finally {
    await fsp.rm(lockPath, { recursive: true, force: true });
  }
}

function sleep(ms) {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}
